"""Add indexes for performance

Revision ID: aa615b0fb086
Revises: c5f8a596fb26
Create Date: 2025-05-03 11:10:26.280491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa615b0fb086'
down_revision = 'c5f8a596fb26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_composition', schema=None) as batch_op:
        batch_op.create_index('ix_body_composition_client_id_date', ['client_id', 'date'], unique=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index('ix_clients_name', ['name'], unique=False)
        batch_op.create_index('ix_clients_team_id', ['team_id'], unique=False)

    with op.batch_alter_table('health_questionnaires', schema=None) as batch_op:
        batch_op.create_index('ix_health_questionnaires_client_id_date', ['client_id', 'submission_date'], unique=False)

    with op.batch_alter_table('physical_tests', schema=None) as batch_op:
        batch_op.create_index('ix_physical_tests_client_id_date', ['client_id', 'date'], unique=False)
        batch_op.create_index('ix_physical_tests_client_id_type', ['client_id', 'test_type'], unique=False)

    with op.batch_alter_table('progress_photos', schema=None) as batch_op:
        batch_op.create_index('ix_progress_photos_client_id_date', ['client_id', 'upload_date'], unique=False)

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_training_sessions_client_id_date', ['client_id', 'date'], unique=False)
        batch_op.create_index('ix_training_sessions_program_id', ['workout_program_id'], unique=False)

    with op.batch_alter_table('workout_programs', schema=None) as batch_op:
        batch_op.create_index('ix_workout_programs_client_id_date', ['client_id', 'date'], unique=False)
        batch_op.create_index('ix_workout_programs_team_id_date', ['team_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_programs', schema=None) as batch_op:
        batch_op.drop_index('ix_workout_programs_team_id_date')
        batch_op.drop_index('ix_workout_programs_client_id_date')

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_training_sessions_program_id')
        batch_op.drop_index('ix_training_sessions_client_id_date')

    with op.batch_alter_table('progress_photos', schema=None) as batch_op:
        batch_op.drop_index('ix_progress_photos_client_id_date')

    with op.batch_alter_table('physical_tests', schema=None) as batch_op:
        batch_op.drop_index('ix_physical_tests_client_id_type')
        batch_op.drop_index('ix_physical_tests_client_id_date')

    with op.batch_alter_table('health_questionnaires', schema=None) as batch_op:
        batch_op.drop_index('ix_health_questionnaires_client_id_date')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index('ix_clients_team_id')
        batch_op.drop_index('ix_clients_name')

    with op.batch_alter_table('body_composition', schema=None) as batch_op:
        batch_op.drop_index('ix_body_composition_client_id_date')

    # ### end Alembic commands ###
